#Hibernate
hibernate.dialect=org.hibernate.dialect.OracleDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true

# datasource
datasource.driver=oracle.jdbc.driver.OracleDriver
datasource.url=jdbc:oracle:thin:@host.docker.internal:1521/xe
datasource.username=heart_rate
datasource.password=heart_rate

# rest
health-tracker.api.base-url=http://localhost:8082

#Kafka configuration
spring.kafka.bootstrap-servers=broker:9092