#Hibernate
hibernate.dialect=org.hibernate.community.dialect.Oracle10gDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true

# datasource
spring.datasource.driver=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=heart_rate
spring.datasource.password=heart_rate

# rest
health-tracker.api.base-url=http://localhost:8083

#Kafka configuration
spring.kafka.bootstrap-servers=localhost:29092