# datasource
spring.datasource.driver=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/HEART_RATE
spring.datasource.username=root
spring.datasource.password=sergey2000

#Hibernate
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto=validate
