alter session set "_ORACLE_SCRIPT"=true;

--DROP USER HEART_RATE CASCADE;

CREATE USER HEART_RATE_TEST
IDENTIFIED BY heart_rate
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "HEART_RATE_TEST" ;

-- ROLES
GRANT "RESOURCE" TO "HEART_RATE_TEST" ;
GRANT UNLIMITED TABLESPACE TO "HEART_RATE_TEST";

