#Hibernate
hibernate.dialect=org.hibernate.community.dialect.Oracle10gDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true

# rest
health-tracker.api.base-url=http://localhost:8083

#Kafka configuration
spring.kafka.bootstrap-servers=localhost:29092

spring.liquibase.change-log=classpath:db/liquibase-changelog.xml
spring.liquibase.contexts=!initial-data