DROP TABLE HEART_RATE.HEART_RATE;
DROP TABLE HEART_RATE.PERSON;
DROP TABLE HEART_RATE.HELP;
DROP TABLE HEART_RATE.TOPIC;


CREATE TABLE HEART_RATE.PERSON(
ID INT NOT NULL PRIMARY KEY auto_increment,
FIRST_NAME VARCHAR(20) NOT NULL,
MIDDLE_NAME VARCHAR(20),
SECOND_NAME VARCHAR(20),
COUNTRY VARCHAR (30),
CITY VARCHAR (30),
BIRTHDATE DATE,
PHONE VARCHAR(30),
MOBILE_PHONE VARCHAR(30),
EMAIL VARCHAR(30)
);

CREATE TABLE HEART_RATE.HEART_RATE(
ID INT NOT NULL PRIMARY KEY auto_increment,
UPPER_PRESSURE INT NOT NULL,
LOWER_PRESSURE INT NOT NULL,
CONCREATE_DATE DATE NOT NULL,
PERSON_ID INT NOT NULL
);

ALTER TABLE HEART_RATE.HEART_RATE ADD CONSTRAINT fk_heart_rate_person_id FOREIGN KEY(PERSON_ID) REFERENCES heart_rate.PERSON(ID) ON DELETE CASCADE;


CREATE TABLE HEART_RATE.HELP(
ID INT NOT NULL PRIMARY KEY auto_increment,
NAME VARCHAR(30) NOT NULL,
DESCRIPTION text NOT NULL,
TOPIC_ID INT NOT NULL
);


CREATE TABLE HEART_RATE.TOPIC(
ID INT NOT NULL PRIMARY KEY auto_increment,
NAME VARCHAR(30) NOT NULL
);

ALTER TABLE HEART_RATE.HELP ADD CONSTRAINT fk_help_topic_id FOREIGN KEY(TOPIC_ID) REFERENCES heart_rate.TOPIC(ID) ON DELETE CASCADE;

insert into heart_rate.TOPIC(NAME) values('PERSON');
insert into heart_rate.TOPIC(NAME) values('HEART_RATE');

insert into heart_rate.help (NAME, description, TOPIC_ID) values ('Add Heart Rate', 'adds heart rate ', 2);

insert into heart_rate.help (NAME, description, TOPIC_ID) values ('Add Heart Rate By Id', 'adds heart rate. Insted of name and second name persons id can be inserted', 2);
